// Dim_Employee - Version avec RegionID
let
    // Partie 1 : SQL Server
    DonneesSQL = Sql.Database("localhost", "Northwind"),
    EmployeesSQL = DonneesSQL{[Schema="dbo",Item="Employees"]}[Data],
    TerritoriesSQL = DonneesSQL{[Schema="dbo",Item="Territories"]}[Data],
    EmployeeTerritoriesSQL = DonneesSQL{[Schema="dbo",Item="EmployeeTerritories"]}[Data],
    
    // Partie 2 : Jointures SQL Server (sans table Region)
    JointureET = Table.NestedJoin(EmployeesSQL, {"EmployeeID"}, EmployeeTerritoriesSQL, {"EmployeeID"}, "EmpTerr", JoinKind.LeftOuter),
    #"EmpTerr développé" = Table.ExpandTableColumn(JointureET, "EmpTerr", {"TerritoryID"}, {"TerritoryID"}),
    JointureT = Table.NestedJoin(#"EmpTerr développé", {"TerritoryID"}, TerritoriesSQL, {"TerritoryID"}, "Terr", JoinKind.LeftOuter),
    #"Terr développé" = Table.ExpandTableColumn(JointureT, "Terr", {"TerritoryDescription", "RegionID"}, {"TerritoryDescription", "RegionID"}),
    
    // Partie 3 : Transformation SQL Server
    SQLPourEmployes = Table.SelectColumns(#"Terr développé",{"EmployeeID", "LastName", "FirstName", "TerritoryDescription", "RegionID"}),
    SQLRenomme = Table.RenameColumns(SQLPourEmployes,{
        {"LastName", "Nom"},
        {"FirstName", "Prenom"}, 
        {"TerritoryDescription", "Territory"},
        {"RegionID", "RegionID"}
    }),
    SQLAvecSource = Table.AddColumn(SQLRenomme, "source_prod", each "SQL Server", type text),
    SQLAvecDescri = Table.AddColumn(SQLAvecSource, "TerritoryDescri", each [Territory], type text),
    SQLFinal = Table.SelectColumns(SQLAvecDescri,{"EmployeeID", "Nom", "Prenom", "Territory", "TerritoryDescri", "RegionID", "source_prod"}),
    
    // Partie 4 : Excel - FICHIER "Employees.xlsx"
    DonneesExcel = Excel.Workbook(File.Contents("C:\Users\GAB Informatique\Documents\Master 2\TBI\TP2\Employees.xlsx"), null, true),
    FeuilleExcel = DonneesExcel{[Item="Employees",Kind="Sheet"]}[Data],
    EnTetetesPromus = Table.PromoteHeaders(FeuilleExcel, [PromoteAllScalars=true]),
    
    // Détection automatique des colonnes Excel
    ColonnesDisponibles = Table.ColumnNames(EnTetetesPromus),
    ColonneEmployeeID = if List.Contains(ColonnesDisponibles, "EmployeeID") then "EmployeeID"
                   else if List.Contains(ColonnesDisponibles, "Employee Id") then "Employee Id"
                   else if List.Contains(ColonnesDisponibles, "ID") then "ID"
                   else ColonnesDisponibles{0},
                   
    ColonneLastName = if List.Contains(ColonnesDisponibles, "LastName") then "LastName"
                 else if List.Contains(ColonnesDisponibles, "Last Name") then "Last Name"
                 else if List.Contains(ColonnesDisponibles, "Nom") then "Nom"
                 else ColonnesDisponibles{1},
                 
    ColonneFirstName = if List.Contains(ColonnesDisponibles, "FirstName") then "FirstName"
                  else if List.Contains(ColonnesDisponibles, "First Name") then "First Name"
                  else if List.Contains(ColonnesDisponibles, "Prénom") then "Prénom"
                  else ColonnesDisponibles{2},

    // Renommage des colonnes Excel
    ExcelRenomme = Table.RenameColumns(EnTetetesPromus,{
        {ColonneEmployeeID, "EmployeeID"},
        {ColonneLastName, "Nom"},
        {ColonneFirstName, "Prenom"}
    }),
    
    // Gestion des territoires pour Excel
    ExcelAvecTerritoire = if List.Contains(ColonnesDisponibles, "TerritoryDescription") then 
        Table.RenameColumns(ExcelRenomme,{{"TerritoryDescription", "Territory"}})
    else if List.Contains(ColonnesDisponibles, "Territory") then 
        ExcelRenomme
    else 
        Table.AddColumn(ExcelRenomme, "Territory", each "Non spécifié", type text),
        
    // Gestion de RegionID pour Excel
    ExcelAvecRegionID = if List.Contains(ColonnesDisponibles, "RegionID") then 
        ExcelAvecTerritoire
    else if List.Contains(ColonnesDisponibles, "Region ID") then 
        Table.RenameColumns(ExcelAvecTerritoire,{{"Region ID", "RegionID"}})
    else if List.Contains(ColonnesDisponibles, "Region") then 
        // Convertir Region en RegionID si nécessaire
        Table.AddColumn(ExcelAvecTerritoire, "RegionID", 
            each if [Region] = "Eastern" then 1
            else if [Region] = "Western" then 2
            else if [Region] = "Northern" then 3
            else if [Region] = "Southern" then 4
            else 0, Int64.Type)
    else 
        Table.AddColumn(ExcelAvecTerritoire, "RegionID", each 0, Int64.Type),
    
    // Supprimer la colonne Region si elle existe
    ColonnesApresRegion = Table.ColumnNames(ExcelAvecRegionID),
    ExcelSansRegion = if List.Contains(ColonnesApresRegion, "Region") then 
        Table.RemoveColumns(ExcelAvecRegionID,{"Region"})
    else ExcelAvecRegionID,
    
    ExcelAvecDescri = Table.AddColumn(ExcelSansRegion, "TerritoryDescri", each [Territory], type text),
    ExcelAvecSource = Table.AddColumn(ExcelAvecDescri, "source_prod", each "Excel", type text),
    ExcelFinal = Table.SelectColumns(ExcelAvecSource,{"EmployeeID", "Nom", "Prenom", "Territory", "TerritoryDescri", "RegionID", "source_prod"}),
    
    // Partie 5 : Fusion COMPLÈTE
    FusionComplete = Table.Combine({SQLFinal, ExcelFinal}),
    
    // Partie 6 : Index final
    IndexAjoute = Table.AddIndexColumn(FusionComplete, "id_seqEmployee", 1, 1),
    
    // Partie 7 : Sélection finale
    ColonnesFinales = Table.SelectColumns(IndexAjoute,{
        "id_seqEmployee", "EmployeeID", "source_prod", "Nom", "Prenom", 
        "Territory", "TerritoryDescri", "RegionID"
    }),
    ColonneRenommee = Table.RenameColumns(ColonnesFinales,{{"EmployeeID", "id_employee_prod"}})
in
    ColonneRenommee