// DimClient - AVEC suppression doublons
let
    // Partie 1 : SQL Server
    DonneesSQL = Sql.Database("localhost", "Northwind"),
    TableCustomersSQL = DonneesSQL{[Schema="dbo",Item="Customers"]}[Data],
    SQLPourClients = Table.SelectColumns(TableCustomersSQL,{"CustomerID", "CompanyName", "City"}),
    SQLAvecSource = Table.AddColumn(SQLPourClients, "source_prod", each "SQL Server", type text),
    SQLRenomme = Table.RenameColumns(SQLAvecSource,{
        {"CustomerID", "id_client_prod"},
        {"CompanyName", "CompanyName"},
        {"City", "City"}
    }),
    
    // Partie 2 : Excel - FEUILLE "Customers"
    DonneesExcel = Excel.Workbook(File.Contents("C:\Users\GAB Informatique\Documents\Master 2\TBI\TP2\Customers.xlsx"), null, true),
    FeuilleExcel = DonneesExcel{[Item="Customers",Kind="Sheet"]}[Data],
    EnTetetesPromus = Table.PromoteHeaders(FeuilleExcel, [PromoteAllScalars=true]),
    ExcelAvecSource = Table.AddColumn(EnTetetesPromus, "source_prod", each "Excel", type text),
    
    // Détection automatique des colonnes Excel
    ColonnesDisponibles = Table.ColumnNames(EnTetetesPromus),
    ColonneCustomerID = if List.Contains(ColonnesDisponibles, "CustomerID") then "CustomerID"
                   else if List.Contains(ColonnesDisponibles, "Customer Id") then "Customer Id"
                   else if List.Contains(ColonnesDisponibles, "ID") then "ID"
                   else ColonnesDisponibles{0},
                   
    ColonneCompanyName = if List.Contains(ColonnesDisponibles, "CompanyName") then "CompanyName"
                   else if List.Contains(ColonnesDisponibles, "Company Name") then "Company Name"
                   else if List.Contains(ColonnesDisponibles, "Entreprise") then "Entreprise"
                   else ColonnesDisponibles{1},
                   
    ColonneCity = if List.Contains(ColonnesDisponibles, "City") then "City"
             else if List.Contains(ColonnesDisponibles, "Ville") then "Ville"
             else ColonnesDisponibles{2},
    
    ExcelRenomme = Table.RenameColumns(ExcelAvecSource,{
        {ColonneCustomerID, "id_client_prod"},
        {ColonneCompanyName, "CompanyName"},
        {ColonneCity, "City"}
    }),
    
    // Partie 3 : Fusion AVEC suppression des doublons
    FusionComplete = Table.Combine({SQLRenomme, ExcelRenomme}),
    LignesUniques = Table.Distinct(FusionComplete, {"id_client_prod"}), // Supprime les doublons par ID client
    
    // Partie 4 : Index final
    IndexAjoute = Table.AddIndexColumn(LignesUniques, "id_seqClient", 1, 1),
    
    // Partie 5 : Sélection finale
    ColonnesFinales = Table.SelectColumns(IndexAjoute,{"id_seqClient", "id_client_prod", "source_prod", "CompanyName", "City"})
in
    ColonnesFinales