// Dim_Temps - Une ligne par combinaison année/mois UNIQUE
let
    // Partie 1 : SQL Server
    DonneesSQL = Sql.Database("localhost", "Northwind"),
    TableOrdersSQL = DonneesSQL{[Schema="dbo",Item="Orders"]}[Data],
    SQLPourTemps = Table.SelectColumns(TableOrdersSQL,{"OrderDate"}),
    SQLAvecSource = Table.AddColumn(SQLPourTemps, "Source", each "SQL Server", type text),
    SQLRenomme = Table.RenameColumns(SQLAvecSource,{{"OrderDate", "DateSource"}}),
    
    // Partie 2 : Excel - FEUILLE "Orders"
    DonneesExcel = Excel.Workbook(File.Contents("C:\Users\GAB Informatique\Documents\Master 2\TBI\TP2\Orders.xlsx"), null, true),
    FeuilleExcel = DonneesExcel{[Item="Orders",Kind="Sheet"]}[Data],
    EnTetetesPromus = Table.PromoteHeaders(FeuilleExcel, [PromoteAllScalars=true]),
    ExcelAvecSource = Table.AddColumn(EnTetetesPromus, "Source", each "Excel", type text),
    ExcelRenomme = Table.RenameColumns(ExcelAvecSource,{{"OrderDate", "DateSource"}}),
    
    // Partie 3 : Fusion AVEC suppression des doublons de dates
    FusionComplete = Table.Combine({SQLRenomme, ExcelRenomme}),
    DatesUniques = Table.Distinct(FusionComplete, {"DateSource"}), // Supprime les dates en double
    
    // Partie 4 : Transformation
    AnneeAjoutee = Table.AddColumn(DatesUniques, "annee", each Date.Year([DateSource]), Int64.Type),
    MoisAjoute = Table.AddColumn(AnneeAjoutee, "mois", each Date.Month([DateSource]), Int64.Type),
    MoisAnneeFormate = Table.AddColumn(MoisAjoute, "mois_annee", 
        each Text.PadStart(Text.From([mois]), 2, "0") & "-" & Text.From([annee]), type text),
    
    // Partie 5 : SUPPRESSION des doublons année/mois_annee
    CombinaisonsUniques = Table.Distinct(MoisAnneeFormate, {"annee", "mois_annee"}),
    
    // Partie 6 : Index final - Seulement les combinaisons UNIQUES
    IndexAjoute = Table.AddIndexColumn(CombinaisonsUniques, "id_temps", 1, 1),
    
    // Partie 7 : Sélection finale
    ColonnesFinales = Table.SelectColumns(IndexAjoute,{"id_temps", "annee", "mois_annee"})
in
    ColonnesFinales