// TF_Commande - Version adaptative
let
    // Partie 1 : SQL Server - Orders
    DonneesSQL = Sql.Database("localhost", "Northwind"),
    TableOrdersSQL = DonneesSQL{[Schema="dbo",Item="Orders"]}[Data],
    SQLPourCommandes = Table.SelectColumns(TableOrdersSQL,{"OrderID", "OrderDate", "EmployeeID", "CustomerID", "ShippedDate"}),
    SQLAvecSource = Table.AddColumn(SQLPourCommandes, "Source", each "SQL", type text),
    
    // Partie 2 : Excel - Version adaptative
    DonneesExcel = Excel.Workbook(File.Contents("C:\Users\GAB Informatique\Documents\Master 2\TBI\TP2\Orders_FAIT.xlsx"), null, true),
    FeuilleExcel = DonneesExcel{[Item="Orders",Kind="Sheet"]}[Data],
    EnTetetesPromus = Table.PromoteHeaders(FeuilleExcel, [PromoteAllScalars=true]),
    
    // Détection automatique des colonnes
    ColonnesDisponibles = Table.ColumnNames(EnTetetesPromus),
    
    // Renommage adaptatif basé sur les colonnes disponibles
    ExcelRenomme = if List.Contains(ColonnesDisponibles, "Employee ID") then
        Table.RenameColumns(EnTetetesPromus,{
            {"Employee ID", "EmployeeID"},
            {"Customer ID", "CustomerID"}, 
            {"Order Date", "OrderDate"},
            {"Shipped Date", "ShippedDate"}
        })
    else if List.Contains(ColonnesDisponibles, "EmployeeID") then
        EnTetetesPromus // Déjà bons noms
    else
        // Si les colonnes ont d'autres noms, utiliser les premières colonnes
        Table.RenameColumns(EnTetetesPromus,{
            {ColonnesDisponibles{0}, "EmployeeID"},
            {ColonnesDisponibles{1}, "CustomerID"},
            {ColonnesDisponibles{2}, "OrderDate"},
            {ColonnesDisponibles{3}, "ShippedDate"}
        }),
    
    // Ajouter OrderID manquant pour Excel
    ExcelAvecOrderID = Table.AddColumn(ExcelRenomme, "OrderID", 
        each "EXCEL-" & Text.From([EmployeeID]) & "-" & Text.From([CustomerID]) & "-" & Text.From([OrderDate]), type text),
    ExcelAvecSource = Table.AddColumn(ExcelAvecOrderID, "Source", each "Excel", type text),
    
    // Partie 3 : Fusion COMPLÈTE des données
    FusionComplete = Table.Combine({SQLAvecSource, ExcelAvecSource}),
    
    // Partie 4 : SUPPRESSION DES DOUBLONS 
    LignesUniques = Table.Distinct(FusionComplete, {"OrderID"}),
    
    // Partie 5 : Création des colonnes pour la jointure avec Dim_temps
    AnneeMoisAjoutes = Table.AddColumn(LignesUniques, "annee_commande", each Date.Year([OrderDate]), Int64.Type),
    MoisAnneeAjoute = Table.AddColumn(AnneeMoisAjoutes, "mois_annee_commande", 
        each Text.PadStart(Text.From(Date.Month([OrderDate])), 2, "0") & "-" & Text.From(Date.Year([OrderDate])), type text),
    
    // Partie 6 : Jointure avec Dim_temps (LEFT OUTER)
    DimTemps = Dim_temps,
    JointureTemps = Table.Join(MoisAnneeAjoute, {"annee_commande", "mois_annee_commande"}, DimTemps, {"annee", "mois_annee"}, JoinKind.LeftOuter),
    
    // Partie 7 : Jointure avec Dim_employee (LEFT OUTER)
    DimEmployee = Dim_employee,
    EmployeeSansDoublons = Table.Distinct(Table.SelectColumns(DimEmployee, {"id_employee_prod", "id_seqEmployee"}), {"id_employee_prod"}),
    JointureEmployee = Table.Join(JointureTemps, "EmployeeID", EmployeeSansDoublons, "id_employee_prod", JoinKind.LeftOuter),
    
    // Partie 8 : Jointure avec Dim_client (LEFT OUTER)
    DimClient = Dim_client,
    ClientSansDoublons = Table.Distinct(Table.SelectColumns(DimClient, {"id_client_prod", "id_seqClient"}), {"id_client_prod"}),
    JointureClient = Table.Join(JointureEmployee, "CustomerID", ClientSansDoublons, "id_client_prod", JoinKind.LeftOuter),
    
    // Partie 9 : Calcul des métriques
    CommandesLivrees = Table.AddColumn(JointureClient, "nbr_commande_livrees", 
        each if [ShippedDate] <> null then 1 else 0, Int64.Type),
        
    CommandesNonLivrees = Table.AddColumn(CommandesLivrees, "nbr_commande_non_livrees", 
        each if [ShippedDate] = null then 1 else 0, Int64.Type),
    
    // Partie 10 : Index final
    IndexAjoute = Table.AddIndexColumn(CommandesNonLivrees, "id_seq_fait", 1, 1),
    
    // Partie 11 : Sélection des colonnes finales
    ColonnesFinales = Table.SelectColumns(IndexAjoute,{
        "id_seq_fait", 
        "id_temps", 
        "id_seqEmployee", 
        "id_seqClient", 
        "nbr_commande_livrees", 
        "nbr_commande_non_livrees"
    })
in
    ColonnesFinales